apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: topology
  namespace: desire6g-smo
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 32007
  selector:
    run: topology
status:
  loadBalancer: {}
---
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: topology
  name: topology
  namespace: desire6g-smo
spec:
  containers:
  - image: harbor.nbfc.io/desire6g/desire6g-topology
    name: topology
    ports:
    - containerPort: 8000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
